In [45]:
import random
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import h5py
from flask import Flask, request, render_template, jsonify
import tensorflow as tf
from keras.models import load_model
from nltk import word_tokenize
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing import sequence
import pickle

In [4]:
model = tf.keras.models.load_model("app_model.hdf5")
tokenizer = pickle.load(open('tokenizer.pkl', 'rb'))
app = Flask(__name__, static_url_path="")

In [16]:
#@app.route('/')
def index():
    """Return the main page."""
    return render_template('index.html')

In [27]:
# vectorizes and tokenizes the input
#@app.route('/')
def tokenize_input(user_input):
    """Converts input text to word vectors for model"""
    words = word_tokenize(user_input)
    list_tokenized = tokenizer.texts_to_sequences(words)
    X_t = sequence.pad_sequences(list_tokenized, maxlen=100)
    return X_t

In [53]:
#@app.route('/predict', methods=['GET', 'POST'])
def predict(user_input):
    """Return a random prediction."""
    #data = request.json
    X_t = tokenize_input(user_input)
    prediction = model.predict(X_t)
    return prediction[0]

In [35]:
prediction = model.predict(tokenize_input(user_input))

In [48]:
prediction

array([[9.9960572e-01, 3.9431846e-04],
       [9.9802953e-01, 1.9704951e-03],
       [9.9970454e-01, 2.9548033e-04],
       [9.9931967e-01, 6.8036636e-04],
       [9.9953842e-01, 4.6156318e-04]], dtype=float32)

In [47]:
user_input = 'run this'
tokenize_input(user_input)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0, 521],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [54]:
predict('hello')

array([9.9960572e-01, 3.9431846e-04], dtype=float32)